/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RyanGUIProject1;
import my.zhugui1.ZhuGUI1;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ZhuGUI1.main(args);
    }
}
